"""SQLAlchemy models; importing this module registers all tables on Base.metadata."""

from app.models.entities import (
    AlertEvent,
    AuditLog,
    CleaningEvent,
    CleaningTask,
    Device,
    DeviceEvent,
    Facility,
    HygieneScore,
    Incident,
    NotificationPreference,
    Organization,
    PasswordResetToken,
    ScoreInput,
    Sensor,
    SensorReading,
    TelemetryEvent,
    User,
    UserSession,
    Washroom,
)

__all__ = [
    "AlertEvent",
    "AuditLog",
    "CleaningEvent",
    "CleaningTask",
    "Device",
    "DeviceEvent",
    "Facility",
    "HygieneScore",
    "Incident",
    "NotificationPreference",
    "Organization",
    "PasswordResetToken",
    "ScoreInput",
    "Sensor",
    "SensorReading",
    "TelemetryEvent",
    "User",
    "UserSession",
    "Washroom",
]
