from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable

OUT = Path('output/pdf/IoTSense_UI_Redesign_Implementation_Plan.pdf')
OUT.parent.mkdir(parents=True, exist_ok=True)
W, H = A4
M = 18*mm
white=colors.white; mist=colors.HexColor('#f5f5f7'); frost=colors.HexColor('#fafafc')
hair=colors.HexColor('#d6d6d6'); ink=colors.HexColor('#1d1d1f'); slate=colors.HexColor('#707070')
blue=colors.HexColor('#0066cc'); action=colors.HexColor('#0071e3'); amber=colors.HexColor('#986000')
styles=getSampleStyleSheet()
def sty(name, **kw): styles.add(ParagraphStyle(name=name, **kw))
sty('K',fontName='Helvetica-Bold',fontSize=8,leading=11,textColor=blue,spaceAfter=10)
sty('Cover',fontName='Helvetica-Bold',fontSize=34,leading=38,textColor=ink,spaceAfter=12)
sty('Sub',fontName='Helvetica',fontSize=15,leading=21,textColor=slate,spaceAfter=16)
sty('H1x',fontName='Helvetica-Bold',fontSize=22,leading=26,textColor=ink,spaceAfter=9,keepWithNext=True)
sty('H2x',fontName='Helvetica-Bold',fontSize=13,leading=17,textColor=ink,spaceBefore=9,spaceAfter=5,keepWithNext=True)
sty('Bodyx',fontName='Helvetica',fontSize=8.5,leading=12,textColor=ink,spaceAfter=5)
sty('Smallx',fontName='Helvetica',fontSize=7.5,leading=10,textColor=slate,spaceAfter=4)
sty('Cellx',fontName='Helvetica',fontSize=7,leading=9,textColor=ink)
sty('Headx',fontName='Helvetica-Bold',fontSize=7,leading=9,textColor=ink)
sty('Callx',fontName='Helvetica',fontSize=8.5,leading=12,textColor=ink)
P=lambda s,n='Bodyx': Paragraph(s,styles[n])
def bullets(items):
    rows=[[P('<font color="#0066cc">-</font> '+x)] for x in items]
    t=Table(rows,colWidths=[W-2*M-3*mm],hAlign='LEFT')
    t.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),2),('RIGHTPADDING',(0,0),(-1,-1),1),('TOPPADDING',(0,0),(-1,-1),1),('BOTTOMPADDING',(0,0),(-1,-1),1)]))
    return t
def tbl(rows,widths):
    data=[[c if isinstance(c,Paragraph) else P(str(c),'Headx' if ri==0 else 'Cellx') for c in row] for ri,row in enumerate(rows)]
    t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT')
    cmd=[('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),('LINEBELOW',(0,0),(-1,-1),.35,hair),('BACKGROUND',(0,0),(-1,0),mist)]
    for i in range(2,len(rows),2): cmd.append(('BACKGROUND',(0,i),(-1,i),frost))
    t.setStyle(TableStyle(cmd)); return t
def call(title,body):
    t=Table([[P('<b>'+title+'</b><br/>'+body,'Callx')]],colWidths=[W-2*M])
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),mist),('LINEBEFORE',(0,0),(0,-1),2.5,blue),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8)])); return t
def head(n,title,desc): return [P(n,'K'),P(title,'H1x'),P(desc,'Bodyx')]
def frame(c,d):
    c.saveState()
    if d.page>1:
        c.setStrokeColor(hair); c.line(M,H-11*mm,W-M,H-11*mm)
        c.setFont('Helvetica-Bold',7); c.setFillColor(ink); c.drawString(M,H-8.5*mm,'IOTSENSE  /  UI REDESIGN PLAN')
        c.setFont('Helvetica',7); c.setFillColor(slate); c.drawRightString(W-M,H-8.5*mm,'Implementation blueprint')
    c.setStrokeColor(hair); c.line(M,11*mm,W-M,11*mm)
    c.setFont('Helvetica',6.5); c.setFillColor(slate); c.drawString(M,7.5*mm,'Prepared 30 September 2026 | Current frontend + supplied style reference')
    c.drawRightString(W-M,7.5*mm,str(d.page)); c.restoreState()

S=[]
# Cover
S += [Spacer(1,19*mm),P('PRODUCT DESIGN AND DELIVERY BLUEPRINT / 01','K'),P('IoTSense UI redesign','Cover'),P('Implementation plan for a production-ready facility monitoring experience, using the supplied Apple gallery style as a visual reference.','Sub'),Spacer(1,9*mm),call('DESIGN INTENT','Make a dense operational dashboard feel calm and readable through clear hierarchy, open space, precise blue actions, and restrained surfaces.'),Spacer(1,5*mm),call('SCOPE','All 20 current routes, shared navigation, every visible action, ESP32 state, responsive behavior, accessibility, and release readiness.'),Spacer(1,12*mm),P('A practical adaptation, not a pixel-for-pixel copy','H2x'),P('The reference describes a product launch page with editorial scale, centered imagery, sparse controls, and large storytelling sections. IoTSense is an operational tool with readings, alerts, tables, and work queues. This plan translates the reference tokens and restraint into a compact monitoring workspace without sacrificing scanning speed, device workflows, or accessibility.'),P('Document purpose','H2x'),P('Use this blueprint to sequence design and engineering work, review scope, and accept the redesigned interface. Route names reflect the current frontend in frontend/src/App.tsx and frontend/src/app/routes.ts.'),Spacer(1,7*mm),HRFlowable(width='100%',thickness=.5,color=hair),Spacer(1,5*mm),P('Version 1.0 | 30 September 2026','Smallx'),PageBreak()]

# Direction and tokens
S += head('01 / DIRECTION','Executive summary','Redesign the full application around one coherent design system, then bring every route and control into the same visual and interaction standard.')
S += [call('Recommended visual direction','Gallery White (#ffffff) is the default content surface; Studio Mist (#f5f5f7) groups sections; Paper Frost (#fafafc) is for opened menus. Use #d6d6d6 hairlines and #e6e6e8 disabled fills. Text uses #1d1d1f and #707070. Reserve #0066cc for links and #0071e3 for compact primary actions. Operational status colors remain semantic.'),P('Production ready means','H2x'),bullets(['Every route shares tokens, typography, control patterns, responsive behavior, and page states.','Every visible control has a defined outcome, loading state, success state, and error path.','Live ESP32 readings, simulated BME680, sample records, stale data, and backend data are clearly distinguished.','Keyboard use, focus, labels, landmarks, contrast, reduced motion, and screen-reader announcements are acceptance criteria.','Consequential actions confirm intent; errors explain recovery; state persists where users expect it.']),P('Scope and constraints','H2x'),P('Current scope is a frontend MVP with direct USB serial for MQ-3 and MQ-135, simulated BME680 values, and sample operations/admin pages. Production workflows for provisioning, identity, persisted alerts, audit history, and cross-user settings need matching backend contracts and authorization. SF Pro availability varies by OS; use the supplied system stack and licensed fonts only.'),PageBreak()]
S += head('02 / VISUAL SYSTEM','Reference translation','Use the supplied tokens as a foundation, tuned for a monitoring console rather than a consumer product launch page.')
S += [tbl([['Reference rule','IoTSense translation'],['Color','White page and panel surfaces; Mist full-width bands; Frost popovers; hairline borders; ink/slate text; blue links and compact primary action. Add semantic success, warning, danger, offline and focus tokens.'],['Typography','SF Pro/system stack. Workspace heading 28-32px (40px maximum); 17px explanatory copy; 14px dense content; 12px utility controls. Do not use 80px hero type inside authenticated workspace.'],['Spacing','4px base. Related control gap 20px; panel padding 28px wide and 16-20px compact; major workspace gaps 48-64px. Reserve 90px for public storytelling.'],['Shape','28px for featured media/story panels; 20px navigation container; 10px controls/links; pill radius for compact actions. Keep operational rows compact.'],['Elevation','Prefer surface contrast and 1px outlines. Remove broad shadows. Focus and selection use visible outlines. Use elevation sparingly for transient overlays.'],['Imagery','Real installation imagery for public landing/setup only. Operational pages prioritize values, tables and trends; diagrams only when they explain a task.'],['Motion','Brief transitions, no animation on every sensor tick. Respect reduced-motion preferences. Never use motion/color as the only status cue.']],[42*mm,W-2*M-42*mm]),P('Token adoption checklist','H2x'),bullets(['Move palette, type, radius and spacing into named CSS custom properties.','Use the specified system fallbacks; do not bundle fonts without a license.','Keep #0066cc for text links and #0071e3 for compact primary actions.','Validate contrast for text and icons, including semantic status colors.','Use responsive type and spacing from 320px to wide desktop.']),call('Data-layout exception','The reference discourages conventional card stacks. IoTSense still needs KPI values, sensor readouts, tables, and task queues. Keep these flat, aligned, low-chrome, and easy to scan.'),PageBreak()]

# Shell
S += head('03 / FOUNDATION','Shell and interaction standards','Build the shared shell and control behavior before route content to make navigation and interaction consistent.')
S += [tbl([['Area','Standard','States'],['Shell','Persistent desktop side navigation; keyboard-operable mobile drawer; breadcrumbs, facility, notifications and profile. Preserve browser back/forward.','Current route; open/closed; loading; access denied.'],['Facility selector','Accessible name and selected value; authorized options; selection filters page data and persists in route or view state.','Loading; selected; none; error; permission-limited.'],['Buttons/links','Links navigate; buttons act. Icon-only actions get accessible names. Primary, secondary, text, destructive and quiet variants.','Hover; focus; pressed; disabled; busy; outcome.'],['Search/filters','Debounce remote search; allow clear; preserve query on return; expose active filter count.','Empty; active; no results; loading; reset.'],['Forms','Persistent labels, hints, inline validation, server errors, unsaved change handling and submission progress.','Untouched; focus; invalid; submit; saved/error.'],['Tables/charts','Semantic headers, sort state, named row actions, responsive alternative. Charts have text summary and data table/export.','Skeleton; populated; empty; error; stale.'],['Feedback/dialogs','Toast for brief success; banner/inline for persistent errors; dialog only for decisions. Focus trap and restore.','Announced; retryable; escape; confirmed.'],['ESP32','Show permission/port state, connection progress, last sample, retry/disconnect, port-conflict guidance.','Ready; choosing; live; stale; denied; busy; malformed.']],[27*mm,W-2*M-27*mm-31*mm,31*mm]),P('Global control behavior','H2x'),bullets(['Brand/workspace selector: open accessible workspace/facility list; selection is explicit.','Navigation and breadcrumbs: route to target, highlight active page, close mobile drawer, preserve useful scroll/query state.','Mobile menu/scrim: close with Escape and return focus; drawer does not strand focus.','ESP32 connect/disconnect: explain Web Serial permission, retry, status, and COM-port conflict; retain connected history and mark simulated BME.','Notifications/profile: route to destination; menus have names and predictable focus.','Export, date, scenario, tabs, sort, filter, pagination: update the displayed result and announce changes.','Acknowledge, assign, start, complete, verify, provision, save, cancel, delete: check permission, confirm consequential actions, persist via API, report outcome.']),PageBreak()]

# Pages 1
S += head('04 / ROUTE INVENTORY','Page-by-page redesign: workspace','Each existing route gets a clear content hierarchy, interaction outcome, and common states.')
S += [tbl([['Page','Design scope','Actions to implement'],['Landing','Editorial white opening, concise purpose, preview imagery, feature band on Mist, clear data caveat. Avoid unsupported hygiene claims.','Get started; sign in; feature anchors; help links.'],['Login / forgot','Quiet split layout, compact form, labels, validation and privacy copy.','Submit; inline/server errors; password visibility; reset request; return.'],['Dashboard','Facility/live source first; connection, focused KPIs, room table, alerts, trends and next tasks.','Facility; demo scenario; date; export; connect; room/alert/task; view all.'],['Washrooms','Searchable/filterable list with status and score semantics; rows desktop, summaries mobile.','Search; facility/status; sort; reset; open room; paginate.'],['Washroom detail','Room/connection first; score formula/source; exact MQ; simulated BME; voltages; history, causes, active work.','Sensor detail; connection; range; export; open alert/task; back.'],['Sensor detail','Separate raw ADC from derived percentage/voltage; show source and calibration. Simulated BME label.','Sensor; range; download; validated calibration workflow only.'],['Hygiene analysis','Formula, normalization bands, cleaning heuristic, limits, and score contribution. No certification implication.','Range; compare; formula; export; causes/room.'],['Cause identification','Rank evidence-based candidate explanations with signals, period, uncertainty and related route.','Filter; open data; follow-up/acknowledge if supported; export.'],['Analytics','Date/facility controls, units, chart summary, comparisons, and tabular alternative.','Date; metric; compare; download; reset.'],['Alerts/incidents','Severity, room, trigger, timestamp, source, owner and history; never color-only.','Search/filter/sort; acknowledge; assign; resolve/escalate; bulk confirm.'],['Cleaning operations','Queue by due/state with owner, room, priority and context.','Tabs; assign; start; complete; verify; cancel with reason; filter.'],['Cleaning verification','Checklist/evidence, before/after readings, actor/time and result; no false sensor-only certification.','Submit; attach evidence if supported; retry; flag failure; return.']],[31*mm,W-2*M-31*mm-35*mm,35*mm]),PageBreak()]
S += head('04 / ROUTE INVENTORY - CONTINUED','Page-by-page redesign: administration','Administrative routes share the design system while placing safeguards and status clarity first.')
S += [tbl([['Page','Design scope','Actions to implement'],['Devices','Online/stale/offline, firmware, room, last report, capabilities and source.','Search/filter; device detail; assign; pause/retire confirm.'],['Device setup','Guided identity, facility/room, capabilities, installation. Distinguish demo USB from production credential setup.','Draft; create; ID validation; duplicate check; cancel guard; help.'],['Users and roles','Membership table, least privilege definitions and facility scope.','Invite; edit role/scope; deactivate/reactivate; resend.'],['Settings','Facility, thresholds, retention, integrations and preferences grouped by scope.','Save; discard; reset; confirm threshold changes; saved time.'],['Audit logs','Actor, action, target, time, result and detail; immutable event history.','Date/action/actor filters; detail; authorized export; pagination.'],['System health','Service/device summaries, last check, dependency details and incident state.','Refresh; inspect; open alert; safe retry only.'],['Profile','Personal details, notifications, password/session, workspace.','Save; preferences; password; sign out; revoke confirm.'],['Shared overlays','Toast, dialog, filter drawer, facility menu, help, empty/error/access denied.','Close/cancel/confirm/retry with focus and announcement.']],[31*mm,W-2*M-31*mm-35*mm,35*mm]),Spacer(1,7),call('Prototype behavior rule','A static row or local-only toast must not look persisted. Connect the action to an authorized API with full states, or label it demo-only and explain why it is unavailable.'),P('Control audit coverage','H2x'),bullets(['Dashboard: export, scenario/date, room/alert/queue links, facility selector, connect/disconnect.','Washroom: search/filter, status, row navigation, score/sensor links, history range, voltage/calibration details.','Operations: alert acknowledge/resolve/assign, task tabs/actions, verification submit/return.','Administration: device setup, role/invite, settings save/reset, audit filter/export, health refresh, profile/password/sign out.','Every icon button, menu, close affordance, pagination, chart control and mobile navigation action.']),PageBreak()]

# Components/data
S += head('05 / COMPONENTS AND DATA','Reusable patterns and sensor contract','A small complete system makes reliable interaction and consistent sensor presentation easier across all routes.')
S += [tbl([['Component','Required behavior'],['Page header','Title, optional eyebrow/description/action group; responsive wrap; one primary action unless workflow needs more.'],['Navigation','Desktop rail and mobile drawer, breadcrumbs, facility menu, profile/alerts, active route semantics.'],['Buttons','Primary, secondary, text, destructive, icon-only; shared sizes, focus, disabled, busy states.'],['Source/status','Status text and icon; hardware/simulated/sample/stale/API source; updated time.'],['Metric/sensor','Value, label, unit, source, timestamp, optional trend. Raw values separate from derived values.'],['Table/row','Sortable headers, focus/hover/selected states, row navigation separated from actions, responsive fallback.'],['Chart','Units/range/legend, summary, accessible data table, no-data/error, download.'],['Forms','Label, hint, validation, server errors, unsaved changes, keyboard path.'],['Overlay/feedback','Toast/dialog/banner urgency, ARIA announcement, focus management and retry.'],['Page states','Layout-matched skeleton; useful empty state; actionable error; stale marker.']],[38*mm,W-2*M-38*mm]),P('Sensor display and data integrity','H2x'),bullets(['MQ-3 and MQ-135: exact ESP32 raw ADC integer, stated 0-4095 range, timestamp. Never round, clamp, relabel as ppm, or substitute a derived index.','Voltages: show serial-reported precision; browser-calculated voltage must be marked calculated and disclose divider assumptions.','BME680: all simulated temp/humidity/pressure/gas values carry a simulated label in cards, charts, history, and exports.','Score: expose equation, normalization bands and bonus; say it is an MVP estimate, not a certified measure. Keep status thresholds consistent.','History/export preserve per-sample source and timestamp; actual/simulated values are not invisibly blended.']),call('Data safety gate','Stale data must stop looking live. Do not ship views that mix sample, serial, simulated and API data without source labels.'),PageBreak()]

# Phases
S += head('06 / DELIVERY','Phased implementation plan','Ship foundations first, then migrate routes in value groups. Each phase ends with reviewable evidence and acceptance criteria.')
S += [tbl([['Phase','Work and output','Exit criteria'],['0. Audit','Inventory routes, controls, sources, breakpoints and demo actions. Capture screenshots. Resolve API/access dependencies. Produce route/control matrix.','Owner approves scope and demo/production labels; no unexplained control.'],['1. Design system','Tokens; shell; buttons, links, fields, badges, panels, tables, charts, dialogs, toast/banner, responsive patterns. Component gallery.','Gallery approved; shared focus and contrast checked.'],['2. Core workspace','Responsive shell, facility, connection banner, dashboard, washroom list/detail, sensor detail. Preserve exact MQ and simulated BME.','Desktop/tablet/mobile flow reviewed; serial live/stale/denied/disconnect states.'],['3. Analysis/ops','Analysis, causes, analytics, alerts, cleaning operations, verification. Define persistence for range, filtering, assignment and resolution.','Every action works or is demo labeled; source/status persists across routes.'],['4. Admin/auth','Devices/setup, users/roles, settings, audit, health, profile, landing/login/forgot. Wire authorization and validation.','Server enforces role/facility; admin and auth paths report errors/success.'],['5. Hardening','Responsive, accessibility, data-source, interaction and browser checks; performance, release and rollback review.','All release gates pass; owner signs route/control matrix and limits.']],[28*mm,W-2*M-28*mm-35*mm,35*mm]),P('Recommended sequence','H2x'),P('Review the component gallery and dashboard direction first. Then complete one list/detail workflow, one chart, one form, and one consequential action before migrating every route. This finds shared-system gaps early.'),P('Planning estimate','H2x'),P('Approximately 5-8 weeks for an experienced designer-engineer pair, depending on API readiness, content/assets, and admin integration. This is a planning range, not a commitment. Backend, security, calibration, and deployment work may be additional.'),call('Dependencies to resolve in Phase 0','Confirm contracts and authorization for devices, users, alerts, operations, settings, history/exports and facility scope. Confirm Web Serial browser/origin policy. Frontend may proceed against stable contracts, but production claims wait on integration.'),PageBreak()]

# Gates
S += head('07 / ACCEPTANCE','Production readiness gates','A visual refresh is complete only when page states, actions, data integrity, accessibility and responsive behavior meet these gates.')
S += [tbl([['Gate','Acceptance evidence'],['Visual','All 20 routes reviewed at desktop/tablet/mobile sizes. Consistent tokens; no clipping, overlap or unreviewed legacy style.'],['Functional','Route/control matrix exercised. Every visible action navigates, changes state, submits, exports, or is disabled with a reason. Busy, error, retry and confirm states included.'],['Accessibility','Target WCAG 2.2 AA: contrast, keyboard completion, visible focus, landmarks/headings, names/labels/errors, status announcements, non-color cues, zoom/reflow, reduced motion. Automated and manual check.'],['Responsive','Check 320, 375, 768, 1024, wide desktop. Navigation, tables, charts, forms and dialogs usable; no hover-only action.'],['Data integrity','MQ raw equals received ESP32 count. BME is simulated everywhere. Units, timestamps, stale and normalization sources visible. Exports preserve source and score caveats.'],['Security','No secrets in frontend; server enforces role/facility; validate inputs; safe errors; sensitive actions audited; export authorized/minimized.'],['Performance','Set measurable budgets; no layout shift on refresh; expected data volume remains usable; APIs time out/retry; no dead-end loading/error/empty state.'],['Browser/release','Chrome/Edge Web Serial and agreed non-serial browsers; HTTPS/origin; build and dependency review; release notes/rollback plan.']],[35*mm,W-2*M-35*mm]),P('Interaction review','H2x'),bullets(['Click and keyboard-test all actions, including Enter/Space, Escape, focus restoration, and browser back/forward.','Exercise no data, no search result, malformed serial, disconnected/stale sensor, denied permission, busy port, API timeout, validation error and retry.','Verify labels, units and source are visible without tooltip; status/toast announcements match urgency.','Check export date/timezone, active filters, source and range against the visible state.']),P('Release blockers','H2x'),P('Do not call the UI production-ready if operations look saved but are local-only; role checks exist only in the browser; simulated BME looks live; raw MQ display is altered; or stale readings retain a live indicator.'),PageBreak()]

# Ownership & handoff
S += head('08 / HANDOFF','Governance and definition of done','Assign owners and preserve evidence so completion can be reviewed without subjective criteria.')
S += [tbl([['Role','Accountability'],['Product owner','Approve workflows, demo/production boundaries, copy, score caveats, permissions and acceptance.'],['Product designer','Route maps, responsive layouts, component states, interaction specs and visual QA.'],['Frontend engineer','Tokens/components, route migration, client states, accessibility and browser behavior.'],['Backend/firmware','Telemetry contracts, device identity, auth, persisted workflows, errors, source history and firmware agreement.'],['QA/accessibility','Control matrix, viewport checks, keyboard/manual review, API/serial failures and regression evidence.'],['Security/operations','Authorization, sessions, sensitive-action audit, deployment origin and rollback readiness.']],[40*mm,W-2*M-40*mm]),P('Definition of done per route','H2x'),bullets(['Documented user goal, hierarchy and data contract.','Desktop/tablet/mobile plus loading, empty, error, stale and populated states reviewed.','Every visible control is inventoried and implemented.','Keyboard path, focus, names, labels, announcements and contrast reviewed.','Source, freshness, units, raw/derived values, permissions and export behavior correct.','Acceptance evidence and known limits recorded.']),P('Handoff artifacts','H2x'),P('Keep a component library, route/control matrix, API contract links, accessibility checklist, responsive screenshot set and release checklist beside the code. Each review should show a normal and a failure/empty state, including mobile and keyboard behavior.'),P('Reference basis','H2x'),P('Based on the user-supplied Apple - Style Reference and token excerpts, plus the current IoTSense route inventory. This language is adapted for IoTSense and does not imply Apple affiliation.','Smallx'),call('First milestone','Approve the Phase 0 inventory and design-system direction, then implement shell, Dashboard, Washrooms, Washroom Detail and Sensor Detail as the first complete review slice.')]

doc=SimpleDocTemplate(str(OUT),pagesize=A4,leftMargin=M,rightMargin=M,topMargin=19*mm,bottomMargin=17*mm,title='IoTSense UI Redesign Implementation Plan',author='OpenAI Codex',subject='Production-ready UI redesign plan')
doc.build(S,onFirstPage=frame,onLaterPages=frame)
print(f'Created {OUT.resolve()} ({OUT.stat().st_size} bytes)')
